export const profileDescriptions: Record<string, string> = {
    Analyzer: `You are an Analyzer, driven by a deep commitment to accuracy, critical thinking, and an evidence-based approach to decision-making. Analyzers excel in roles that require thorough investigation, fact-checking, and objective assessment, bringing precision and clarity to every decision they make. Your high level of conscientiousness and openness to experience enables you to navigate complex information, sift through data, and arrive at insights grounded in rigorous analysis.`,
    Collaborator: `As a Collaborator, you thrive on building connections, fostering unity, and ensuring that every decision incorporates diverse perspectives. Collaborators are invaluable in environments where teamwork and inclusivity are essential, as your people-focused approach helps create an atmosphere of trust and cooperation. With high levels of agreeableness and extraversion, you are skilled at navigating interpersonal dynamics and adept at finding common ground.`,
    Guardian: `As a Guardian, your decision-making style is centered on caution, forethought, and a strong aversion to unnecessary risk. Guardians excel in roles that demand a careful, measured approach, providing stability and reliability in decision-making processes. You are particularly adept at identifying potential pitfalls and safeguarding against issues before they arise. With your grounded and conscientious nature, you bring an invaluable sense of security to any team.`,
    Explorer: `You are an Explorer, known for your ability to uncover options and consider a wide array of possibilities. Explorers thrive in environments where flexibility, creativity, and adaptability are valued, as they are particularly skilled at generating fresh ideas and surfacing new pathways forward. You excel in strategic and innovation-driven roles, where your talent for envisioning various scenarios helps broaden the decision-making process.`,
    Specialist: `As a Specialist, you bring a depth of expertise and dedication to your work that few others can match. Specialists excel in fields where knowledge, accuracy, and discipline are paramount. Your process-oriented approach and commitment to precision make you a trusted authority in your area, providing dependable guidance based on a solid foundation of specialized knowledge.`,
    Achiever: `As an Achiever, you are driven by a strong focus on outcomes and results. Achievers excel in roles where goal orientation, productivity, and efficient decision-making are essential. With your practical approach, you ensure that tasks are completed effectively and that objectives are met without delay. You are particularly adept at setting priorities, keeping projects on track, and motivating teams to stay focused on results.`,
    Visionary: `You are a Visionary, defined by your ability to think beyond the immediate and imagine transformative possibilities. Visionaries excel in roles where innovation, creativity, and future-focused thinking are essential. With a high level of openness to experience, you thrive in settings that reward unconventional thinking and inspire others to pursue ambitious goals. Your intuitive grasp of what could be guides you as you envision the bigger picture and articulate new directions.`,
    Deliverer: `As a Deliverer, you bring depth and structure to decision-making. Your knowledge and process-oriented approach make you highly reliable in specialized fields where accuracy is essential.`,
}