export const traitDescriptions: Record<string, string> = {
  Outcomes:
    `Score highly in <strong>Outcomes</strong> means you have a natural focus on achieving tangible results. You excel in roles where success is clearly defined and measured, whether that’s through hitting sales targets, completing projects on time, or meeting other performance benchmarks. Your ability to visualize the end goal allows you to break down complex tasks into manageable steps, ensuring that nothing is overlooked on the way to success. This outcome-driven mindset makes you a strong asset in environments where precision and goal achievement are paramount. <br/><br/>
      Your strength in focusing on <strong>Outcomes</strong> often drives you to stay persistent, even in the face of obstacles. While others may get bogged down in details or sidetracked by distractions, you keep your eye on the finish line. This determination not only helps you achieve your own goals but also motivates and guides others around you, making you a natural leader in teams where performance is key. Your ability to balance short-term tasks with long-term objectives ensures that you not only meet expectations but often exceed them. <br/><br/>
      However, it's essential to recognize that a strong focus on <strong>Outcomes</strong> means that you might occasionally overlook the process or miss opportunities to engage more deeply with your team along the way. While results are important, taking time to consider different perspectives and ensuring that others are aligned with the goals can create a more holistic and sustainable path to success. Balancing your outcome-driven approach with a broader view of team dynamics can make your leadership even more impactful.`,
  People:
    `Scoring highly in <strong>People</strong> means your natural ability to engage others is one of your biggest strengths. You excel at building strong relationships and fostering a collaborative environment. In team settings, you are the person who ensures everyone’s voice is heard, making you the glue that holds the group together. This inclusive approach not only enhances team cohesion but also leads to more thoughtful and well-rounded decisions by incorporating diverse perspectives. <br/><br/>
Your focus on <strong>People</strong> makes you particularly adept at navigating interpersonal dynamics within a team. Whether it's mediating conflicts, encouraging quieter members to contribute, or simply making sure everyone feels valued, your ability to consider the human element in decision-making is invaluable. You understand that the best decisions are rarely made in isolation and that engaging with others enriches the process, resulting in outcomes that are more robust and better suited to the needs of all involved. <br/><br/>
However, it’s important to balance this strength with a focus on <strong>Outcomes</strong> or <strong>Process</strong> to ensure that your decisions also meet the necessary goals and are executed efficiently. While fostering positive team dynamics is crucial, maintaining a clear vision for what needs to be accomplished and ensuring that processes are followed can help make your people-focused approach even more effective. By integrating your talent for people engagement with strong goal orientation, you can drive both team success and high-quality decisions.`,
  Risks:
    `Scoring highly in <strong>Risk</strong> means you have a natural ability to foresee potential problems and manage uncertainty effectively. You are often the person who anticipates challenges that others might overlook, and you’re proactive in creating strategies to mitigate those risks before they become issues. This cautious, thoughtful approach to decision-making is invaluable in environments where uncertainty is high, such as crisis management, strategic planning, or innovation-driven industries.<br/><br/>
Your strength in <strong>Risk</strong> management allows you to navigate complex situations with a steady hand. While others might shy away from uncertain paths, your ability to assess both the risks and rewards of a given decision ensures that you take calculated risks. You are neither overly cautious nor reckless, finding the right balance that allows for innovation while safeguarding against potential pitfalls. This measured approach makes you a key player in high-stakes decisions, where the cost of failure can be significant.<br/><br/>
At times, it may be helpful to balance your cautious nature with more flexibility in embracing new opportunities or ideas. While your risk-averse approach often protects against failure, it’s important to remember that some level of risk can lead to breakthrough innovations and unexpected successes. By combining your natural caution with an openness to exploring new options, you can ensure that your decisions not only avoid pitfalls but also capitalize on emerging opportunities.`
,
  Process:
    `Scoring highly in <strong>Process</strong>  means your ability to bring structure and consistency to decision-making is one of your greatest strengths. You excel in environments where clear planning, organization, and step-by-step processes are essential. Your methodical approach ensures that decisions are thoughtful, well-documented, and repeatable. This focus on process often leads to high levels of transparency and accountability, making you a valuable asset in roles that require precision and reliability.<br/><br/>
Your appreciation for  <strong>Process</strong>  means that you thrive in settings where structure is valued, such as project management, operations, or quality control. You are likely the person who ensures that deadlines are met, budgets are adhered to, and all necessary steps are followed before a decision is finalized. Your methodical thinking minimizes errors and ensures that nothing is left to chance, which is particularly important when working on complex projects with many moving parts.<br/><br/>
However, while your strength in  <strong>Process</strong>  brings valuable order to decision-making, it’s also helpful to remain adaptable when situations call for flexibility. Being open to adjustments and occasional improvisation can enhance your ability to respond to unforeseen challenges. Balancing your structured approach with the ability to pivot when needed will ensure that your process-driven mindset remains an asset in both stable and dynamic environments.`,
  Evidence:
    `Scoring highly in <strong>Evidence</strong> means you rely heavily on data and factual information when making decisions. You are methodical and analytical, preferring to base your choices on well-supported facts rather than assumptions or intuition. This trait is essential in roles where accuracy and accountability are paramount, such as research, data analysis, or financial management. Your ability to sift through information and identify the most reliable sources ensures that decisions are grounded in reality.<br/><br/>
Your evidence-based approach means that you thrive in environments where data is readily available, and you excel at turning complex information into actionable insights. Whether you're conducting a detailed analysis or reviewing data to inform a strategy, your decisions are characterized by their thoroughness. Colleagues and teams often rely on your fact-based perspective to validate ideas and ensure that decisions are aligned with the best available information.<br/><br/>
While your reliance on <strong>Evidence</strong> leads to well-informed decisions, it’s also essential to balance data with other decision-making factors, such as intuition or people dynamics. There may be situations where hard evidence is limited, and your ability to incorporate a broader perspective can enhance decision-making. By combining your data-driven approach with flexibility, you ensure that your decisions remain comprehensive and responsive to real-world complexities.`,
  Options:
    `Scoring highly in <strong>Options</strong> means you excel at generating and evaluating multiple alternatives when faced with a decision. Your ability to think creatively and strategically means that you are rarely stuck with a single solution—you often see possibilities where others see limitations. This strength is particularly valuable in innovative roles or environments that require out-of-the-box thinking, such as product development, strategic planning, or creative industries.<br/><br/>
Your focus on exploring <strong>Options</strong> means that you approach decision-making with an open mind, considering various pathways before settling on a final choice. You are likely the person in the room who suggests alternatives that others might not have considered, ensuring that the team has a wide range of choices before making a commitment. This ability to expand the field of possibilities often leads to more robust and innovative outcomes.<br/><br/>
However, it’s important to balance your strength in generating <strong>Options</strong> with the ability to make decisive choices. While exploring multiple possibilities is critical, knowing when to narrow down and commit to a path forward is equally important. By combining your creative thinking with a focus on outcomes, you ensure that your decision-making not only explores the full range of possibilities but also leads to actionable, successful solutions.`,
  Extraversion: `Scoring high in <strong>Extraversion</strong> means you’re energetic, outgoing, and thrive in social situations. You gain energy from interacting with others and are often seen as enthusiastic and assertive in group settings. Your natural confidence in engaging with people makes you a strong communicator and influencer, and you likely enjoy being in roles that require leadership or collaboration.</br></br>
However, while your extraversion helps you excel in environments that value teamwork and social interaction, it’s important to recognize that not every situation will call for constant engagement. Taking moments to reflect quietly and giving others space to share their perspectives can help you balance your sociability with a deeper understanding of group dynamics.</br></br>
In decision-making, your strength lies in gathering input from others and quickly moving toward action. You’re likely to take the lead in group discussions, ensuring that everyone is involved and that decisions are made efficiently. Just remember that taking time to reflect and analyze before jumping into decisions can lead to more thoughtful outcomes.
`,
  Imagination: `Scoring high in <strong>Imagination</strong> means you’re naturally drawn to new ideas, creativity, and a wide range of experiences. You likely enjoy exploring different perspectives and thrive in environments that encourage curiosity and flexibility. Whether it’s through creative projects, intellectual challenges, or simply trying something new, you’re energized by opportunities to think outside the box.</br></br>
While your openness is a great strength in roles that require innovation and adaptability, you may sometimes feel confined in environments that rely heavily on routine or tradition. Balancing your openness with a focus on practicality can help you succeed in more structured settings while still embracing your creative spirit.</br></br>
In decision-making, your ability to generate and evaluate multiple solutions is one of your strongest assets. You’re often the person who sees potential paths that others might miss, which allows you to contribute innovative ideas that lead to breakthroughs. Keep leveraging this strength, but be mindful of grounding your creativity in the specific needs of the situation.
`,
  'Emotional Stability': `Scoring high in <strong>Emotional Stability</strong> means you are calm, composed, and resilient, even in stressful situations. You have a steady temperament, which allows you to handle pressure well and keep a level head when others might be overwhelmed. This emotional resilience makes you a reliable team member in high-pressure environments, such as crisis management or leadership roles.</br></br>
While your emotional stability helps you remain objective and rational, it’s also important to stay aware of your emotions and the emotions of those around you. Being emotionally stable doesn’t mean ignoring feelings, but rather maintaining control over them. By showing empathy and understanding, you can strengthen your relationships and become an even more effective leader or collaborator.</br></br>
In decision-making, your calm demeanor ensures that you don’t make rash choices in stressful situations. You are likely to remain clear-headed and logical, even when faced with uncertainty or conflict. Your ability to stay grounded enables you to make decisions that are not influenced by panic or fear, making you a strong asset in challenging environments.
`,
  Conscientiousness: `Scoring high in <strong>Conscientiousness</strong> means you are organized, dependable, and goal-oriented. You likely take pride in being thorough and disciplined, with a strong sense of responsibility for seeing tasks through to completion. You excel in environments that value structure, planning, and long-term commitment, and others can count on you to deliver high-quality results consistently.</br></br>
While your conscientious nature is a major asset, especially in roles that require precision and accountability, it’s important to be mindful of not becoming too rigid. Flexibility is key in certain situations, and allowing yourself to adapt can open up new opportunities for growth. Your focus on organization is a strength, but don’t be afraid to adjust plans when necessary.</br></br>
In decision-making, your methodical approach ensures that every option is carefully considered before moving forward. Your ability to think through steps and consider potential outcomes leads to well-reasoned, strategic decisions. Keep trusting your process, but remember that sometimes swift action is also valuable when circumstances demand it.
`,
  Agreeableness: `Scoring high in <strong>Agreeableness</strong> means you are compassionate, cooperative, and deeply attuned to the needs of others. You likely prioritize harmony in your relationships and are skilled at navigating social situations with empathy and care. Your ability to listen and consider others’ feelings makes you a great collaborator and an essential part of any team, especially in roles that require diplomacy and cooperation.</br></br>
While your agreeableness helps create positive and inclusive environments, it’s important to balance this with assertiveness when necessary. In some situations, making tough decisions or advocating for your own needs may be required, even if it risks some conflict. Finding that balance between maintaining harmony and standing firm on key issues will enhance your effectiveness.</br></br>
In decision-making, your ability to create consensus is a major asset. You’re often the person who ensures that everyone’s voice is heard, leading to decisions that are more inclusive and reflective of the group. Keep using your people skills to foster collaboration, but don’t shy away from making difficult choices when the situation calls for it.
`
}
